name: Build and Deploy Wiki Client to S3

on:
  push:
    branches:
      - release # This is our production branch

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: "--max-old-space-size=4096"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # We need the full history to correctly determine the version number
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - uses: nrwl/nx-set-shas@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }} # optional: defaults to us-east-1
          SOURCE_DIR: './dist/wiki-client' # optional: defaults to entire repository
